#!/bin/bash




SERVER_HOST_NAME=$1
PORT_NUMBER=$2

NUMBER_MESSAGE=2048
MESSAGE_LENGTH=32768

for TRY_NUMBER in 1 2 3 4 5 6 7 8 9 10
do	
	echo "Processing Try Number:" $TRY_NUMBER 
	echo "MESSAGE LENGTH:" $MESSAGE_LENGTH 
	echo "NUMBER MESSAGE:" $NUMBER_MESSAGE

	echo "./ttcp -t -l$MESSAGE_LENGTH -n$NUMBER_MESSAGE $SERVER_HOST_NAME -p$PORT_NUMBER"
	./ttcp -t -l$MESSAGE_LENGTH -n$NUMBER_MESSAGE $SERVER_HOST_NAME -p$PORT_NUMBER
		
	echo ""
		
done
